version: '2'
services:
  app:
    build: ./backend
    restart: always
    depends_on:
      - db
    ports:
      - 9000:9000
  db:
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=devcamp
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 9001:5432
    volumes:
      - ./db/db-data:/var/lib/postgresql/data